"""Frozen numbers the public site quotes, with their source pinned in one
place -- the same pattern `footy/config.py` uses for TUNE/TEST boundaries:
a number that appears on a page is not computed by the page, it is copied
once from a specific artefact and cited.

**J1_CONFIRMATION_RUN** is the single confirmation run DESIGN_PHASE2.md 5.2
describes ("J1 run（確認・最終）。一度だけ。") -- the numbers below are
transcribed by hand from its report and are not re-derived at site-build
time, on purpose: `reports/` is gitignored (run artefacts, regenerated by
`footy backtest --league jpn1`) so a from-scratch checkout of the public
repo would not have the Markdown file to parse even if a parser existed.
Re-running `footy backtest --league jpn1 --from 2014 --to 2025` reproduces
this exact block (DESIGN_SITE.md 3.4 step 5) -- that reproducibility, not a
build-time file read, is what makes quoting these numbers honest.

If the confirmation run is ever repeated (it should not be -- DESIGN_PHASE2.md
5.3 pre-registers against exactly that), update this module and nothing else.
"""

from __future__ import annotations

J1_CONFIRMATION_RUN = {
    "report_path": "reports/backtest_20260820_175749_jpn1_dc_cal.md",
    "reproduce_cmd": "./bin/footy backtest --league jpn1 --from 2014 --to 2025",
    "season_from": "2014",
    "season_to": "2025-26",
    "n_matches": 3882,
    "n_excluded_no_close": 12,
    "verdict": "PASS",
    "market_desc": "Pinnacle closing price (Shin de-vig)",
    "rps_model": 0.2211,
    "rps_market": 0.2167,
    "rps_climatology": 0.2337,
    "d_rps": 0.0044,
    "d_rps_ci_lo": 0.0026,
    "d_rps_ci_hi": 0.0060,
    "gap_closed_rps": 0.743,
    "murphy_brier_diff": 0.00306,
    "murphy_reliability": -0.00001,
    "murphy_resolution": 0.00290,
    "draw_p_mean": 0.2501,
    "draw_observed": 0.2499,
    "draw_diff": 0.0003,
}

# DESIGN_SITE.md 1.3: the live (forward) record box must say "too few
# matches to mean anything yet" below this n, and never be shown pooled
# with the backtest above.
LIVE_RECORD_MIN_N = 200

SITE_NAME = "Nippon Numbers"

# DESIGN_SITE.md 6.2, verbatim, fixed on every page.
DISCLAIMER = (
    "Statistical model output for research and entertainment. Not betting "
    "advice. Not affiliated with the J.League or any club."
)

# DESIGN_SITE.md 6.4: fixed footer attribution, one place, reused everywhere.
SOURCE_ATTRIBUTION = (
    "Historical results and closing prices: football-data.co.uk. "
    "Pre-match prices via The Odds API (used to time and gate publication; "
    "raw prices are not shown or redistributed)."
)
